[package]
name = "googleads-rs"
version = "0.3.0"
authors = ["Michael S. Huang <mhuang74@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/mhuang74/googleads-rs"
documentation = ""
description = """
A gRPC client library for Google Ads API, generated automatically from the API definition files.
"""
keywords = ["gapi", "grpc", "googleads"]

[lib]

[dependencies]
tonic = { version = "0.6", features = ["tls", "tls-roots"] }
prost = "0.9.0"
prost-types = "0.9.0"

[build-dependencies]
tonic-build = "0.6.2"
